### PR TITLE
Adding analysis of entitlements file, embedded frameworks, watch app and App Extensions

### PR DESCRIPTION
**Pull request by guillemm**
This pull request is to include a couple more features to the gem to analyze the contents of:
* the entitlements file (if any)
* the frameworks located under the Frameworks folder (if any)

There's also a slight reformatting of the files to please Rubocop.

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for the PR @guillemm !

@godrei @trapacska  can you please have a look? ;)

**Comment by guillemm** [comment]
Hi @viktorbenei,
Thanks for the fast reaction.

@godrei, @trapacska: I'm still working on adding some extra features by the way, for app extensions and the watch extension

**Comment by godrei** [comment]
Hi @guillemm ,

sorry for my late response, for first thanks for the PR!

We added tests (rubocop & rspec) to this repo, to allow contributors to safety contribute.

I would ask you to rebase your changes onto current master. You can run the repo test locally by calling `bitrise run ci`. Please fix the rubocop issues (if any) and write some test, which ensures and documents your changes.

Thanks again!

**Comment by viktorbenei** [comment]
Closing due to inactivity - @guillemm feel free to update the PR as mentioned by @godrei and open a new PR, and sorry for the inconvenience

**Pull request closed without merging**
